### ISSUE TITLE
how to configure settings.php correct?

### ISSUE THREAD

**Issue by whallmann** [RoelKroes/wspr2sondehub#1]
Hi
tried to configure the params at the end of the settings.php.
Unfortunelly the names of the values are not conform with the infos eg.in the traquito table.  i have there a value from the header line and Minute and Lane.
could you please tell us what is filled in your values? Thanks
Wolf df7pn

**Comment by RoelKroes** [comment]
Hi Wolf,

wspr2sondehub works totally independent from Traquito. It is a simple tool that translates WSPR transmissions to balloon telemetry by reading the WSPR database, decode the records and posts that to Sondehub. 

It follows the "wisp1" protocol which you can find here: https://hojoham.blogspot.com/2016/05/wisp1-telemetry-revisited.html

The values that you have to enter in the settings file you can find here: http://hojoham.blogspot.com/2016/10/known-flight-ids.html

a short explanation:

You need to find an "empty" slot in the wisp1 table (or borrow one from a ham you know).

Every balloon telemetry record consists of 2 WSPR transmissions from the balloon:

The first WSPR transmission is just a standard WSPR transmission (the callsign transmission)
The second WSPR transmission is a "special" transmission (the telemetry transmission)

If you look at the parameters below (from settings.php):

const CALLSIGN_SLOT = "4";
const TELEMETRY_SLOT = "6";
const FLIGHT_ID_1 = "1";
const FLIGHT_ID_3 = "6";

It means that:

- the callsign transmission should start at minutes that end with a "4". So, hh:04, hh:14, hh:24, hh:34 and so on
- The telemetry transmission should start at minutes that end with a "6". So, hh:06, hh:16, hh:26 and so on
- The flight ID has to do with the first and third character of the WSPR telemetry transmission. So in this case, the telemetry transmission should look like 1X6XXXXXX. This way the software can keep track of the correct balloon. In the "X" there is telemetry encoded.

I also have software for Arduino that you can use in a WSPR balloon tracker: https://github.com/RoelKroes/WSPR_HAB_tracker 

This way you can launch your WSPR balloons totally independent from any third party (except the WSPR database).

I hope this makes it clear!

Best,

Roel.

**Comment by whallmann** [comment]
Thanks Roel
understand this now.
Will setup and check.

73 Wolf

RoelK ***@***.***> schrieb am Mo., 13. Mai 2024, 13:47:

**Comment by whallmann** [comment]
Sorry Roel
there must be a hidden secret.
I set all for wspr DJ2DJ Sonde with horus call DJ2DS-21.    Minute 8 and 0
in channel Q7.  traquito ch 545.
But there is nothing seen here.

73 Wolf

Hallmann (Partenheim) ***@***.***> schrieb am Mo., 13. Mai
2024, 15:36:

**Comment by whallmann** [comment]
All cleared  funny, i wrote 20m into the band instead 14
now is running.
sorry, stupid human.

73 Wolf

Hallmann (Partenheim) ***@***.***> schrieb am Di., 14. Mai
2024, 11:04:

**Comment by RoelKroes** [comment]
Glad you got it working. WSPR and telemetry can be so complicated :-(

Well done!
