### ISSUE TITLE
Tried to modify wspr2sondehub.php so that it can work with zachtek1 tracker, but having some problems

### ISSUE THREAD

**Issue by WildMany** [RoelKroes/wspr2sondehub#2]
I changed the script somewhat and it working sometimes when there are just two messages, for example minut 0 and minute 2. But, it on wsprnet.org are multiple messages, it won't work. Please help. 
[w2s_zachtek.zip](https://github.com/RoelKroes/wspr2sondehub/files/15499440/w2s_zachtek.zip)
Inside attachment is w2s_zachtek.php script that I am using. 

What I did wrong? I changed way of looking for proper messages, and instead searching for telemetry by fist and third letter (ID13), I am trying to use just callsign. That is puzzle that my brain can't solve. So need help.

73, Milan, 9A4GE
---

**Comment by RoelKroes** [comment]
Hi Milan,

Thanks for your question. I will take a look. 

I see your tracker is airborne. Well done.
I will try to get back to you tomorrow.

Roel.

**Comment by WildMany** [comment]
> Hi Milan,
> 
> Thanks for your question. I will take a look.
> 
> I see your tracker is airborne. Well done. I will try to get back to you tomorrow.
> 
> Roel.

Yes, it is airborne. Thanks.

I found one error after which thing stopped working. That was in:

$queryTime = strtotime('now -20 minutes'); //maybe longer in the case of poor reception - was -20

Tried many times to change time span of the query and at some point it become positive value instead '-20' (negative value).
This is just a part of the problem

73, Milan, 9A4GE
---

**Comment by RoelKroes** [comment]
Hi Milan,

You changed a lot in the original script. I am not sure what you want me to check now. Can you be more specific and give some detailed examples? 

Roel.

**Comment by WildMany** [comment]
> Hi Milan,
> 
> You changed a lot in the original script. I am not sure what you want me to check now. Can you be more specific and give some detailed examples?
> 
> Roel.

Okay, seems that the script works fine for ZachTek tracker. Right now, I am trying to make a script for more than one balloon for qrplabs (or traquito, or U4B) trackers. This is pretty huge script by now, just in test phase. Using chatGPT 4o for help, modifying all codes; settings.json, settings.php and wspr2sondehub. 
In settings.json is added more than one balloon, while in settings.php it just call .json file for further processing in wspr2sondehub.
Just want to know, whether you have wish to upload it as your code, or I need to upload it as my code with reference to your original code?
I am doing that way because helping other people to track their balloon (qrplabs, U4B, or traquito tracker) on sondehub, plus my balloon which has zachtek1 tracker. Because LU6AA experiencing frequent problems, my idea is to run it on my Raspberry Pi 400 which is good enough for tracking multiple balloons. Just as it is now, I need to make separate directory for each balloon. And, now after making many changes, testing the resulting single folder/directory script.
The difference between qrplabs and zachtek1 way of calculating altitude and 6 characters grid is significant, so require significant changes. 

73, Milan, 9A4GE

**Comment by RoelKroes** [comment]
Nice work! I hope it works out. 
I was thinking, maybe also consider creating the script for just one balloon and start the script multiple times in different directories? That seems  less complex and easier to understand for people. 
Please upload it as your own code and just add a reference to this project. Let me know if you have finished it!

Roel.

**Comment by WildMany** [comment]
> Nice work! I hope it works out. I was thinking, maybe also consider creating the script for just one balloon and start the script multiple times in different directories? That seems less complex and easier to understand for people. Please upload it as your own code and just add a reference to this project. Let me know if you have finished it!
> 
> Roel.

Okay, after few iterations, the script finally works. Just need time to test it. The problem is that balloon 'AC3AU-2' is still in zone of jamming/spoofing (near Moscow). Also, second balloon 'AC3AU-11' may enter different area near Crimea, where GPS jamming/spoofing is present. Need more time. So far, did not decided whether to leave single database file, or separate them by callsign for each balloon. More work to do. 
Here is .zip file of an 'united' script for at least two balloons which are currently under test tracking.:
[PHP_scripts_wspr2sondehub.zip](https://github.com/user-attachments/files/15525485/PHP_scripts_wspr2sondehub.zip)

73, Milan, 9A4GE

**Comment by WildMany** [comment]
I think it is maybe final version, need more testing. 
[a united wspr2sondehub.zip](https://github.com/user-attachments/files/15526526/a.united.wspr2sondehub.zip)

Now, many balloons may be tracked at once. 
Also, each balloon has its own database.

73, Milan, 9A4GE

**Comment by 9a4ge** [comment]
I changed my repository, new one. 
You may close the issue right now. 
New version that allow more than one balloon and two type of trackers (U4B or qrplabs, zachtek1) is here:
https://github.com/9a4ge/wspr2sondehub/tree/main

73, Milan, 9A4GE

**Comment by RoelKroes** [comment]
Super. Thanks for putting the time in.
